service: remorahchat
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    MSG_TOKEN: ${ssm:/whapi/token}
    CHAT_IDS: ${ssm:/whatsapp/chat_ids}
    MONGO_CONN: ${ssm:/mongo/conn}
    API_KEY: ${ssm:/key}
    SPLITWISE_GROUP_ID: ${ssm:/splitwise/group_id}
    SPLITWISE_KEY: ${ssm:/splitwise/key}
    SPLITWISE_SECRET: ${ssm:/splitwise/secret}

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
