service: remorahchat
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    MSG_TOKEN: ${env:MSG_TOKEN}
    CHAT_IDS: ${env:CHAT_IDS}
    MONGO_CONN: ${env:MONGO_CONN}

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
